# Generated by Django 2.2.28 on 2023-07-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chia_hummus_rojo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hummus',
        ),
        migrations.DeleteModel(
            name='Rojo',
        ),
    ]
