# Generated by Django 2.2.28 on 2023-07-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230710_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vamlu', models.BigIntegerField()),
            ],
        ),
    ]
