# Generated by Django 2.2.28 on 2023-07-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.BigIntegerField()),
            ],
        ),
    ]
